# .github/workflows/ci-checks.yml

name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ci-requirements.txt

      - name: Run Nox
        uses: wntrblm/nox@2025.05.01  
